# Generated by Django 5.0.7 on 2024-09-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
