# Generated by Django 5.2.4 on 2025-11-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_rename_created_post_created_at_comment_created_at_and_more"),
        ("userdetail", "0007_profile_created_at_profile_modified_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="repost",
            unique_together={("user", "post")},
        ),
    ]
