# Generated by Django 5.0.7 on 2024-09-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0003_profile_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='static/profile_images'),
        ),
    ]
