# Generated by Django 5.0.7 on 2024-10-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follow',
            new_name='following',
        ),
    ]
