# Generated by Django 5.0.7 on 2025-07-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdetail", "0005_rename_follow_profile_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
